FROM alpine:latest
LABEL maintainer="Swing Buddy <swingbuddyapp@gmailcom>"
LABEL description="Really simple example of getting output from a docker container"

EXPOSE 80/tcp

CMD ["echo", "It doesn't work yet"]
